using CsvHelper;
using CsvHelper.Configuration;
using LebaApi.Data;
using LebaApi.Models;
using Microsoft.AspNetCore.Mvc;
using System.Globalization;

namespace LebaApi.Controllers
{
    [ApiController]
    [Route("api/[controller]")]
    public class DatasetsController : ControllerBase
    {
        private readonly MongoDbContext _context;

        public DatasetsController(MongoDbContext context)
        {
            _context = context;
        }

        [HttpPost("upload")]
        public async Task<IActionResult> UploadDataset(IFormFile file, [FromForm] string name, [FromForm] string description, [FromForm] string uploaderId)
        {
            if (file == null || file.Length == 0)
                return BadRequest("No file uploaded");

            var dataset = new Dataset
            {
                Name = name,
                Description = description,
                UploadedBy = uploaderId
            };

            await _context.Datasets.InsertOneAsync(dataset);

            var applications = new List<LoanApplication>();
            using (var stream = new StreamReader(file.OpenReadStream()))
            using (var csv = new CsvReader(stream, new CsvConfiguration(CultureInfo.InvariantCulture) { HeaderValidated = null, MissingFieldFound = null }))
            {
                var records = csv.GetRecords<dynamic>();
                foreach (var record in records)
                {
                    try
                    {
                        var app = new LoanApplication
                        {
                            DatasetId = dataset.Id,
                            Age = int.Parse(record.Age.ToString()),
                            Gender = record.Gender,
                            State = record.State,
                            Region = record.Region ?? "Unknown",
                            EducationLevel = record.EducationLevel ?? "Unknown",
                            MaritalStatus = record.MaritalStatus ?? "Unknown",
                            EmploymentType = record.EmploymentType,
                            EmployerCategory = record.EmployerCategory ?? "Unknown",
                            YearsEmployed = int.TryParse(record.YearsEmployed?.ToString(), out int ye) ? ye : 0,
                            MonthlyIncome = decimal.Parse(record.MonthlyIncome.ToString()),
                            CreditScore = int.Parse(record.CreditScore.ToString()),
                            LoanAmount = decimal.TryParse(record.LoanAmount?.ToString(), out decimal la) ? la : 0,
                            ApprovalStatus = record.ApprovalStatus
                        };
                        applications.Add(app);
                    }
                    catch
                    {
                        // Skip malformed rows for MVP
                    }
                }
            }

            if (applications.Any())
            {
                await _context.LoanApplications.InsertManyAsync(applications);
            }

            return Ok(new { Message = "Dataset uploaded successfully", DatasetId = dataset.Id, RecordCount = applications.Count });
        }

        [HttpPost("generate-synthetic")]
        public async Task<IActionResult> GenerateSynthetic([FromBody] GenerateSyntheticRequest request)
        {
            var dataset = new Dataset
            {
                Name = request.Name,
                Description = "Synthetic data generated by L.E.B.A. engine",
                UploadedBy = request.UploaderId
            };

            await _context.Datasets.InsertOneAsync(dataset);

            var random = new Random();
            var applications = new List<LoanApplication>();
            
            string[] genders = { "Male", "Female" };
            string[] employmentTypes = { "Salary Earner", "Trader", "Artisan", "Farmer", "Freelancer", "POS Agent", "Small Business Owner", "Student" };
            string[] regions = { "South West", "South East", "South South", "North Central", "North West", "North East" };

            for (int i = 0; i < request.Count; i++)
            {
                var gender = genders[random.Next(genders.Length)];
                var employment = employmentTypes[random.Next(employmentTypes.Length)];
                
                // Simulate Bias logic: Traders and Farmers have lower base approval chances
                double baseApprovalChance = 0.5;
                if (employment == "Salary Earner") baseApprovalChance += 0.3; // 80% chance
                if (employment == "Trader" || employment == "Farmer") baseApprovalChance -= request.BiasIntensity; // Varies based on bias
                
                if (gender == "Female") baseApprovalChance -= 0.1; // Slight synthetic gender bias

                bool isApproved = random.NextDouble() < baseApprovalChance;

                applications.Add(new LoanApplication
                {
                    DatasetId = dataset.Id,
                    Age = random.Next(18, 65),
                    Gender = gender,
                    State = "Lagos", // Simplified
                    Region = regions[random.Next(regions.Length)],
                    EmploymentType = employment,
                    MonthlyIncome = random.Next(30000, 500000),
                    CreditScore = random.Next(300, 850),
                    ApprovalStatus = isApproved ? "Approved" : "Rejected"
                });
            }

            await _context.LoanApplications.InsertManyAsync(applications);

            return Ok(new { Message = "Synthetic dataset generated successfully", DatasetId = dataset.Id, RecordCount = applications.Count });
        }
    }

    public class GenerateSyntheticRequest
    {
        public string Name { get; set; } = null!;
        public string UploaderId { get; set; } = null!;
        public int Count { get; set; }
        public double BiasIntensity { get; set; } // 0.1 to 0.4
    }
}
